/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetofinal;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.JToolBar;
import javax.swing.SwingUtilities;
import user.User;

/**
 *
 * @author jexkmzww
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        final Login self = this;
        //final JPanel x = this;

        buttonEntrar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String login = textFieldLogin.getText();
                String password = textFieldPass.getText();
                try {
                    if (checkboxRobo.isSelected()) {
                        User user = Users.login(login, password);
                        new Application(new MovieCatalog(user));
                        ((JFrame)SwingUtilities.getRoot(self)).dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Por favor, confirme que você não é um robô!");
                    }
                } catch (Exception ex) {
                    textFieldLogin.setBackground(Color.red);
                    textFieldPass.setBackground(Color.red);
                    JOptionPane.showMessageDialog(null, "Login/senha incorretos!");
                }
            }
        });

        textFieldLogin.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (textFieldLogin.getBackground().equals(Color.red)) {
                    textFieldLogin.setText("");
                    textFieldPass.setText("");
                }
                textFieldLogin.setBackground(Color.white);
                textFieldPass.setBackground(Color.white);
            }

            @Override
            public void focusLost(FocusEvent e) {

            }
        });
        textFieldPass.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (textFieldLogin.getBackground().equals(Color.red)) {
                    textFieldLogin.setText("");
                    textFieldPass.setText("");
                }
                textFieldLogin.setBackground(Color.white);
                textFieldPass.setBackground(Color.white);
            }

            @Override
            public void focusLost(FocusEvent e) {

            }
        });

        buttonSair.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                ((JFrame)SwingUtilities.getRoot(self)).dispose();

            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        textFieldLogin = new javax.swing.JTextField();
        buttonEntrar = new javax.swing.JButton();
        labelLogin = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        buttonSair = new javax.swing.JButton();
        checkboxRobo = new javax.swing.JCheckBox();
        textFieldPass = new javax.swing.JPasswordField();

        jToolBar1.setRollover(true);

        textFieldLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldLoginActionPerformed(evt);
            }
        });

        buttonEntrar.setText("Entrar");

        labelLogin.setText("Login");

        labelPassword.setText("Password");

        buttonSair.setText("Sair");

        checkboxRobo.setSelected(true);
        checkboxRobo.setText("Não sou um robô");
        checkboxRobo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxRoboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(labelLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(checkboxRobo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonSair)
                                .addGap(26, 26, 26)
                                .addComponent(buttonEntrar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelPassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(textFieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLogin)
                    .addComponent(textFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPassword)
                    .addComponent(textFieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkboxRobo)
                    .addComponent(buttonSair)
                    .addComponent(buttonEntrar))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldLoginActionPerformed

    }//GEN-LAST:event_textFieldLoginActionPerformed

    private void checkboxRoboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxRoboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxRoboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEntrar;
    private javax.swing.JButton buttonSair;
    private javax.swing.JCheckBox checkboxRobo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JTextField textFieldLogin;
    private javax.swing.JPasswordField textFieldPass;
    // End of variables declaration//GEN-END:variables

    public JButton getButtonEntrar() {
        return buttonEntrar;
    }

    public JButton getButtonSair() {
        return buttonSair;
    }

    public JCheckBox getCheckboxRobo() {
        return checkboxRobo;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JToolBar getjToolBar1() {
        return jToolBar1;
    }

    public JLabel getLabelLogin() {
        return labelLogin;
    }

    public JLabel getLabelPassword() {
        return labelPassword;
    }

    public JTextField getTextFieldLogin() {
        return textFieldLogin;
    }

    public JPasswordField getTextFieldPass() {
        return textFieldPass;
    }

}
