/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetofinal;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import movie.Movies;
import user.User;

/**
 *
 * @author jexkmzww
 */
public class MovieCatalog extends javax.swing.JPanel {

    /**
     * Creates new form MovieCatalog
     */
    
    private JFrame app;
    private User user;
    
    
    public MovieCatalog(User user) {
        initComponents();
        this.user = user;
        
        ImageIcon image = new ImageIcon(getClass().getResource("fastNFurious.jpg"));
        labelImageFastNFurious.setIcon(image);

        ImageIcon image2 = new ImageIcon(getClass().getResource("123horas.jpg"));
        labelImage123horas.setIcon(image2);

        ImageIcon image3 = new ImageIcon(getClass().getResource("aHospedeira.jpg"));
        labelImageAHospedeira.setIcon(image3);

        ImageIcon image4 = new ImageIcon(getClass().getResource("meuNomeNaoEJohnny.jpg"));
        labelImageMeuNomeNaoEJohnny.setIcon(image4);

        ImageIcon image5 = new ImageIcon(getClass().getResource("starWars.jpg"));
        labelImageStarWars.setIcon(image5);

        ImageIcon image6 = new ImageIcon(getClass().getResource("theDarkKnight.jpg"));
        labelImageTheDarkKnight.setIcon(image6);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDialog1 = new javax.swing.JDialog();
        labelImageFastNFurious = new javax.swing.JLabel();
        labelImage123horas = new javax.swing.JLabel();
        labelImageAHospedeira = new javax.swing.JLabel();
        labelImageMeuNomeNaoEJohnny = new javax.swing.JLabel();
        labelImageStarWars = new javax.swing.JLabel();
        labelImageTheDarkKnight = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        labelImageFastNFurious.setText("Image");
        labelImageFastNFurious.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelImageFastNFuriousMouseClicked(evt);
            }
        });

        labelImage123horas.setText("Image");
        labelImage123horas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelImage123horasMouseClicked(evt);
            }
        });

        labelImageAHospedeira.setText("Image");
        labelImageAHospedeira.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelImageAHospedeiraMouseClicked(evt);
            }
        });

        labelImageMeuNomeNaoEJohnny.setText("Image");
        labelImageMeuNomeNaoEJohnny.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelImageMeuNomeNaoEJohnnyMouseClicked(evt);
            }
        });

        labelImageStarWars.setText("Image");
        labelImageStarWars.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelImageStarWarsMouseClicked(evt);
            }
        });

        labelImageTheDarkKnight.setText("Image");
        labelImageTheDarkKnight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelImageTheDarkKnightMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelImageFastNFurious, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelImageAHospedeira, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelImageStarWars, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelImage123horas, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelImageMeuNomeNaoEJohnny, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelImageTheDarkKnight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelImageMeuNomeNaoEJohnny, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelImage123horas, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelImageFastNFurious, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelImageAHospedeira, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelImageTheDarkKnight, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelImageStarWars, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void labelImageFastNFuriousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelImageFastNFuriousMouseClicked
        openMovieDetail(0);        
    }//GEN-LAST:event_labelImageFastNFuriousMouseClicked

    private void labelImage123horasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelImage123horasMouseClicked
        openMovieDetail(1);
    }//GEN-LAST:event_labelImage123horasMouseClicked

    private void labelImageMeuNomeNaoEJohnnyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelImageMeuNomeNaoEJohnnyMouseClicked
        openMovieDetail(2);
    }//GEN-LAST:event_labelImageMeuNomeNaoEJohnnyMouseClicked

    private void labelImageAHospedeiraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelImageAHospedeiraMouseClicked
        openMovieDetail(3);
    }//GEN-LAST:event_labelImageAHospedeiraMouseClicked

    private void labelImageStarWarsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelImageStarWarsMouseClicked
        openMovieDetail(4);
    }//GEN-LAST:event_labelImageStarWarsMouseClicked

    private void labelImageTheDarkKnightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelImageTheDarkKnightMouseClicked
        openMovieDetail(5);
    }//GEN-LAST:event_labelImageTheDarkKnightMouseClicked

    private void openMovieDetail (int index){
        new Application(new MovieDetails(Movies.get(index), user));     
        ((JFrame)SwingUtilities.getRoot(this)).dispose();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog jDialog1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelImage123horas;
    private javax.swing.JLabel labelImageAHospedeira;
    private javax.swing.JLabel labelImageFastNFurious;
    private javax.swing.JLabel labelImageMeuNomeNaoEJohnny;
    private javax.swing.JLabel labelImageStarWars;
    private javax.swing.JLabel labelImageTheDarkKnight;
    // End of variables declaration//GEN-END:variables

}
