/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetofinal;

import java.awt.Color;
import java.awt.event.ActionEvent;

import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.time.Instant;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import movie.Movie;
import user.User;

/**
 *
 * @author jose.assis
 */
public class MovieDetails extends javax.swing.JPanel {

    /**
     * Creates new form MovieDetails
     */
    private User user;
    private Movie movie;

    public MovieDetails(Movie movie, User user) {

        initComponents();

        this.user = user;
        this.movie = movie;

        labelDataLancamento.setText(movie.getDataLancamento());
        labelClassificacao.setText(movie.getClassificacao());
        labelDirecao.setText(movie.getDirecao());
        labelGenero.setText(movie.getGenero());
        labelIdioma.setText(movie.getIdioma());
        labelNacionalidade.setText(movie.getNacionalidade());
        labelSinopse.setText("SINOPSE VEM AQUI MANO");
        labelPreco.setText(String.valueOf(movie.calculaPreco(user.isPremium())));
        
        if (user.isPremium()){
            labelPreco.setForeground(Color.GREEN);
        }

        ImageIcon image = new ImageIcon(getClass().getResource(movie.getImage()));
        labelMovie.setIcon(image);

        buttonVoltar.addActionListener(this::openMovieCatalog);

        buttonComprar.addActionListener(this::buyTicketMovie);

    }

    private void openMovieCatalog(ActionEvent e) {
        new Application(new MovieCatalog(user));
        ((JFrame) SwingUtilities.getRoot(this)).dispose();
    }

    private void buyTicketMovie(ActionEvent e) {
        double userMoney = user.getMoney();
        double moviePrice = movie.calculaPreco(user.isPremium());

        if (userMoney < moviePrice) {
            JOptionPane.showMessageDialog(null, "Você não tem dinheiro para esta operação.");
            return;
        }

        JOptionPane.showMessageDialog(null, "Ticket comprado com sucesso!");

        issueMovieTicket();

        user.setMoney(userMoney - moviePrice);
    }

    private void issueMovieTicket() {
        try {
            String timeNow = Instant.now().toString();
            String fileName = "Ingresso_" + user.getLogin() + "_" + getDate() + ".txt";
            StringBuilder stringbuilder = new StringBuilder("Comprovante de ingresso");
            stringbuilder.append("\nFilme: " + movie.getNameMovie());
            stringbuilder.append("\nPreço: " + movie.calculaPreco(user.isPremium()));
            stringbuilder.append("\nHora da compra: " + timeNow);
            String ticketMessage = stringbuilder.toString().replaceAll("\n", System.lineSeparator());
            OutputStream f = new FileOutputStream(fileName);
            f.write(ticketMessage.getBytes());
            f.close();
        } catch (IOException ex) {
            Logger.getLogger(MovieDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private String getDate() {
        return String.valueOf(Instant.now().getEpochSecond());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelMovie = new javax.swing.JLabel();
        labelDataLancamento = new javax.swing.JLabel();
        labelDirecao = new javax.swing.JLabel();
        labelClassificacao = new javax.swing.JLabel();
        labelGenero = new javax.swing.JLabel();
        labelNacionalidade = new javax.swing.JLabel();
        labelSinopse = new javax.swing.JLabel();
        labelIdioma = new javax.swing.JLabel();
        buttonComprar = new javax.swing.JButton();
        buttonVoltar = new javax.swing.JButton();
        labelPreco = new javax.swing.JLabel();

        setToolTipText("");

        labelMovie.setText("movieImage");

        labelDataLancamento.setText("dataLançamento");

        labelDirecao.setText("direcao");

        labelClassificacao.setText("classificacao");

        labelGenero.setText("genero");

        labelNacionalidade.setText("nacionalidade");

        labelSinopse.setText("sinopse");

        labelIdioma.setText("idioma");

        buttonComprar.setText("Comprar");

        buttonVoltar.setText("Voltar");

        labelPreco.setText("preco");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(labelMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelClassificacao)
                    .addComponent(labelDataLancamento)
                    .addComponent(labelDirecao)
                    .addComponent(labelGenero)
                    .addComponent(labelNacionalidade)
                    .addComponent(labelIdioma)
                    .addComponent(labelPreco))
                .addContainerGap(252, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonVoltar)
                        .addGap(31, 31, 31)
                        .addComponent(buttonComprar))
                    .addComponent(labelSinopse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelDataLancamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelDirecao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelClassificacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelGenero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNacionalidade)
                        .addGap(7, 7, 7)
                        .addComponent(labelIdioma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelPreco)))
                .addGap(24, 24, 24)
                .addComponent(labelSinopse, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonComprar)
                    .addComponent(buttonVoltar))
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonComprar;
    private javax.swing.JButton buttonVoltar;
    private javax.swing.JLabel labelClassificacao;
    private javax.swing.JLabel labelDataLancamento;
    private javax.swing.JLabel labelDirecao;
    private javax.swing.JLabel labelGenero;
    private javax.swing.JLabel labelIdioma;
    private javax.swing.JLabel labelMovie;
    private javax.swing.JLabel labelNacionalidade;
    private javax.swing.JLabel labelPreco;
    private javax.swing.JLabel labelSinopse;
    // End of variables declaration//GEN-END:variables
}
